In [1]:
In [1]: import numpy as np

In [2]: import pandas as pd

In [4]:
pd.read_csv("villes_france.csv")

c:\users\maxim\.virtualenvs\villes-1rr_tubx\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,1,01,ozan,OZAN,ozan.1,Ozan,O250,OSN,01190,284,...,93,6.6,4.91667,46.3833,2866,51546,+45456,462330,170,205
0,2,1,cormoranche-sur-saone,CORMORANCHE-SUR-SAONE,cormoranche sur saone,Cormoranche-sur-Saône,C65652625,KRMRNXSRSN,01290,123,...,107,9.85,4.83333,46.23330,2772.0,51379.0,44953.0,461427.0,168.0,211.0
1,3,1,plagne-01,PLAGNE,plagne,Plagne,P425,PLKN,01130,298,...,20,6.20,5.73333,46.18330,3769.0,51324.0,54342.0,461131.0,560.0,922.0
2,4,1,tossiat,TOSSIAT,tossiat,Tossiat,T230,TST,01250,422,...,138,10.17,5.31667,46.13330,3309.0,51268.0,51854.0,460828.0,244.0,501.0
3,5,1,pouillat,POUILLAT,pouillat,Pouillat,P430,PLT,01250,309,...,14,6.23,5.43333,46.33330,3435.0,51475.0,52542.0,461938.0,333.0,770.0
4,6,1,torcieu,TORCIEU,torcieu,Torcieu,T620,TRS,01230,421,...,65,10.72,5.40000,45.91670,3398.0,51025.0,52343.0,455521.0,257.0,782.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36694,36825,976,sada,SADA,sada,Sada,S300,ST,97640,616,...,933,10.92,45.10470,-12.84860,NaN,NaN,NaN,NaN,NaN,NaN
36695,36826,976,tsingoni,TSINGONI,tsingoni,Tsingoni,T2525,TSNKN,97680,617,...,300,34.76,45.10700,-12.78970,NaN,NaN,NaN,NaN,NaN,NaN
36696,36827,971,st-barthelemy,SAINT BARTHELEMY,st barthelemy,Saint-Barthélemy,S5316345,SNTPR0LM,97133,123,...,372,24.00,-62.83330,17.91670,NaN,NaN,NaN,NaN,NaN,NaN
36697,36828,971,st-martin,SAINT MARTIN,st martin,Saint-Martin,S535635,SNTMRTN,97150,127,...,695,53.20,18.09130,-63.08290,NaN,NaN,NaN,NaN,NaN,NaN
36698,36830,975,st-pierre-et-miquelon,SAINT PIERRE ET MIQUELON,st pierre et miquelon,Saint-Pierre-et-Miquelon,S531635245,SNTPR,97500,501,...,25,242.00,46.71070,1.71819,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
city = pd.read_csv(‘villes_france.csv’, names=[‘ville_id’, ‘ville_departement’, ‘ville_slug’, ‘ville_nom’, ‘ville_nom_simple’, ‘ville_nom_reel’, ‘ville_nom_soundex’, ‘ville_nom_metaphone’, ‘ville_code_postal’, ‘ville_commune’, ‘ville_code_commune’, ‘ville_arrondissement’, ‘ville_canton’, ‘ville_amdi’, ‘ville_population_2010’, ‘ville_population_1999’, ‘ville_population_2012’, ‘ville_densite_2010’, ‘ville_surface’, ‘ville_longitude_de’, ‘ville_latitude_deg’, ‘ville_longitude_grd’, ‘ville_latitude_grd’, ‘ville_longitude_dms’, ‘ville_latitude_dms’, ‘ville_zmin’, ‘ville_zmax’], header=None)

SyntaxError: invalid character in identifier (<ipython-input-5-df1fb5996a6b>, line 1)

In [6]:
city = pd.read_csv(‘villes_france.csv’, names=[‘ville_id’, ‘ville_departement’, ‘ville_slug’, ‘ville_nom’, ‘ville_nom_simple’, ‘ville_nom_reel’, ‘ville_nom_soundex’, ‘ville_nom_metaphone’, ‘ville_code_postal’, ‘ville_commune’, ‘ville_code_commune’, ‘ville_arrondissement’, ‘ville_canton’, ‘ville_amdi’, ‘ville_population_2010’, ‘ville_population_1999’, ‘ville_population_2012’, ‘ville_densite_2010’, ‘ville_surface’, ‘ville_longitude_de’, ‘ville_latitude_deg’, ‘ville_longitude_grd’, ‘ville_latitude_grd’, ‘ville_longitude_dms’, ‘ville_latitude_dms’, ‘ville_zmin’, ‘ville_zmax’], header=None)

SyntaxError: invalid character in identifier (<ipython-input-6-0c97e96c2e8e>, line 1)

In [8]:
city = pd.read_csv('villes_france.csv', names=['ville_id', 'ville_departement', 'ville_slug', 'ville_nom', 'ville_nom_simple', 'ville_nom_reel', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_code_postal', 'ville_commune', 'ville_code_commune', 'ville_arrondissement', 'ville_canton', 'ville_amdi', 'ville_population_2010', 'ville_population_1999', 'ville_population_2012', 'ville_densite_2010', 'ville_surface', 'ville_longitude_de', 'ville_latitude_deg', 'ville_longitude_grd', 'ville_latitude_grd', 'ville_longitude_dms', 'ville_latitude_dms', 'ville_zmin', 'ville_zmax'], header=None)

In [9]:
city = pd.read_csv('villes_france.csv', names=['ville_id', 'ville_departement', 'ville_slug', 'ville_nom', 'ville_nom_simple', 'ville_nom_reel', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_code_postal', 'ville_commune', 'ville_code_commune', 'ville_arrondissement', 'ville_canton', 'ville_amdi', 'ville_population_2010', 'ville_population_1999', 'ville_population_2012', 'ville_densite_2010', 'ville_surface', 'ville_longitude_de', 'ville_latitude_deg', 'ville_longitude_grd', 'ville_latitude_grd', 'ville_longitude_dms', 'ville_latitude_dms', 'ville_zmin', 'ville_zmax'], header=None)

In [10]:
names=['ville_id', 'ville_departement', 'ville_slug', 'ville_nom', 'ville_nom_simple', 'ville_nom_reel', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_code_postal', 'ville_commune', 'ville_code_commune', 'ville_arrondissement', 'ville_canton', 'ville_amdi', 'ville_population_2010', 'ville_population_1999', 'ville_population_2012', 'ville_densite_2010', 'ville_surface', 'ville_longitude_de', 'ville_latitude_deg', 'ville_longitude_grd', 'ville_latitude_grd', 'ville_longitude_dms', 'ville_latitude_dms', 'ville_zmin', 'ville_zmax'], header=None)

SyntaxError: invalid syntax (<ipython-input-10-d9fc6b6cff13>, line 1)

In [11]:
city = pd.read_csv('villes_france.csv')

In [12]:
names=['ville_id', 'ville_departement', 'ville_slug', 'ville_nom', 'ville_nom_simple', 'ville_nom_reel', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_code_postal', 'ville_commune', 'ville_code_commune', 'ville_arrondissement', 'ville_canton', 'ville_amdi', 'ville_population_2010', 'ville_population_1999', 'ville_population_2012', 'ville_densite_2010', 'ville_surface', 'ville_longitude_de', 'ville_latitude_deg', 'ville_longitude_grd', 'ville_latitude_grd', 'ville_longitude_dms', 'ville_latitude_dms', 'ville_zmin', 'ville_zmax'], header=None)

SyntaxError: invalid syntax (<ipython-input-12-d9fc6b6cff13>, line 1)

In [13]:
city = pd.read_csv('villes_france.csv', names=['ville_id', 'ville_departement', 'ville_slug', 'ville_nom', 'ville_nom_simple', 'ville_nom_reel', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_code_postal', 'ville_commune', 'ville_code_commune', 'ville_arrondissement', 'ville_canton', 'ville_amdi', 'ville_population_2010', 'ville_population_1999', 'ville_population_2012', 'ville_densite_2010', 'ville_surface', 'ville_longitude_de', 'ville_latitude_deg', 'ville_longitude_grd', 'ville_latitude_grd', 'ville_longitude_dms', 'ville_latitude_dms', 'ville_zmin', 'ville_zmax'], header=None)

In [14]:
city

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_de,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
0,1,1,ozan,OZAN,ozan,Ozan,O250,OSN,01190,284,...,93,6.60,4.91667,46.38330,2866.0,51546.0,45456.0,462330.0,170.0,205.0
1,2,1,cormoranche-sur-saone,CORMORANCHE-SUR-SAONE,cormoranche sur saone,Cormoranche-sur-Saône,C65652625,KRMRNXSRSN,01290,123,...,107,9.85,4.83333,46.23330,2772.0,51379.0,44953.0,461427.0,168.0,211.0
2,3,1,plagne-01,PLAGNE,plagne,Plagne,P425,PLKN,01130,298,...,20,6.20,5.73333,46.18330,3769.0,51324.0,54342.0,461131.0,560.0,922.0
3,4,1,tossiat,TOSSIAT,tossiat,Tossiat,T230,TST,01250,422,...,138,10.17,5.31667,46.13330,3309.0,51268.0,51854.0,460828.0,244.0,501.0
4,5,1,pouillat,POUILLAT,pouillat,Pouillat,P430,PLT,01250,309,...,14,6.23,5.43333,46.33330,3435.0,51475.0,52542.0,461938.0,333.0,770.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36695,36825,976,sada,SADA,sada,Sada,S300,ST,97640,616,...,933,10.92,45.10470,-12.84860,NaN,NaN,NaN,NaN,NaN,NaN
36696,36826,976,tsingoni,TSINGONI,tsingoni,Tsingoni,T2525,TSNKN,97680,617,...,300,34.76,45.10700,-12.78970,NaN,NaN,NaN,NaN,NaN,NaN
36697,36827,971,st-barthelemy,SAINT BARTHELEMY,st barthelemy,Saint-Barthélemy,S5316345,SNTPR0LM,97133,123,...,372,24.00,-62.83330,17.91670,NaN,NaN,NaN,NaN,NaN,NaN
36698,36828,971,st-martin,SAINT MARTIN,st martin,Saint-Martin,S535635,SNTMRTN,97150,127,...,695,53.20,18.09130,-63.08290,NaN,NaN,NaN,NaN,NaN,NaN
36699,36830,975,st-pierre-et-miquelon,SAINT PIERRE ET MIQUELON,st pierre et miquelon,Saint-Pierre-et-Miquelon,S531635245,SNTPR,97500,501,...,25,242.00,46.71070,1.71819,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
pd.sort_values(by = 'population'[0:49])

AttributeError: module 'pandas' has no attribute 'sort_values'

In [16]:
city

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_de,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
0,1,1,ozan,OZAN,ozan,Ozan,O250,OSN,01190,284,...,93,6.60,4.91667,46.38330,2866.0,51546.0,45456.0,462330.0,170.0,205.0
1,2,1,cormoranche-sur-saone,CORMORANCHE-SUR-SAONE,cormoranche sur saone,Cormoranche-sur-Saône,C65652625,KRMRNXSRSN,01290,123,...,107,9.85,4.83333,46.23330,2772.0,51379.0,44953.0,461427.0,168.0,211.0
2,3,1,plagne-01,PLAGNE,plagne,Plagne,P425,PLKN,01130,298,...,20,6.20,5.73333,46.18330,3769.0,51324.0,54342.0,461131.0,560.0,922.0
3,4,1,tossiat,TOSSIAT,tossiat,Tossiat,T230,TST,01250,422,...,138,10.17,5.31667,46.13330,3309.0,51268.0,51854.0,460828.0,244.0,501.0
4,5,1,pouillat,POUILLAT,pouillat,Pouillat,P430,PLT,01250,309,...,14,6.23,5.43333,46.33330,3435.0,51475.0,52542.0,461938.0,333.0,770.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36695,36825,976,sada,SADA,sada,Sada,S300,ST,97640,616,...,933,10.92,45.10470,-12.84860,NaN,NaN,NaN,NaN,NaN,NaN
36696,36826,976,tsingoni,TSINGONI,tsingoni,Tsingoni,T2525,TSNKN,97680,617,...,300,34.76,45.10700,-12.78970,NaN,NaN,NaN,NaN,NaN,NaN
36697,36827,971,st-barthelemy,SAINT BARTHELEMY,st barthelemy,Saint-Barthélemy,S5316345,SNTPR0LM,97133,123,...,372,24.00,-62.83330,17.91670,NaN,NaN,NaN,NaN,NaN,NaN
36698,36828,971,st-martin,SAINT MARTIN,st martin,Saint-Martin,S535635,SNTMRTN,97150,127,...,695,53.20,18.09130,-63.08290,NaN,NaN,NaN,NaN,NaN,NaN
36699,36830,975,st-pierre-et-miquelon,SAINT PIERRE ET MIQUELON,st pierre et miquelon,Saint-Pierre-et-Miquelon,S531635245,SNTPR,97500,501,...,25,242.00,46.71070,1.71819,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
city.sort_values(by = 'ville_population_2012', ascending = False)

SyntaxError: invalid syntax (<ipython-input-23-ae2e3e200985>, line 1)

In [24]:
print(city['ville_population_2012'])

0          500
1         1000
2          100
3         1400
4          100
         ...
36695    10195
36696    10454
36697     8938
36698    36979
36699     6080
Name: ville_population_2012, Length: 36700, dtype: int64

In [29]:
listCity = city.sort_values(by = 'ville_population_2012', ascending = False)
listCity

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_de,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
30437,30438,75,paris,PARIS,paris,Paris,P620,PRS,75001-75002-75003-75004-75005-75006-75007-7500...,56,...,21288,105.40,2.344450,48.8600,9.0,54289.0,22040.0,485136.0,0.0,0.0
4439,4440,13,marseille,MARSEILLE,marseille,Marseille,M624,MRSL,13001-13002-13003-13004-13005-13006-13007-1300...,55,...,3535,240.62,5.376390,43.2967,3377.0,48107.0,52235.0,431748.0,0.0,640.0
28152,28153,69,lyon,LYON,lyon,Lyon,L500,LYN,69001-69002-69003-69004-69005-69006-69007-6900...,123,...,10117,47.87,4.841390,45.7589,2783.0,50843.0,45029.0,454532.0,162.0,312.0
11718,11719,31,toulouse,TOULOUSE,toulouse,Toulouse,T420,TLS,31000-31100-31200-31300-31400-31500,555,...,3734,118.30,1.433330,43.6000,-994.0,48449.0,12631.0,433616.0,115.0,263.0
2049,2050,6,nice,NICE,nice,Nice,N200,NS,06000-06100-06200-06300,88,...,4773,71.92,7.250000,43.7000,5480.0,48558.0,71606.0,434207.0,0.0,520.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3900,3901,11,pomy,POMY,pomy,Pomy,P500,PM,11300,294,...,9,6.00,2.050000,43.0500,-301.0,47844.0,20355.0,430333.0,297.0,560.0
3897,3898,11,bourigeole,BOURIGEOLE,bourigeole,Bourigeole,B624,BRJL,11300,46,...,5,9.08,2.133330,42.9833,-225.0,47765.0,20801.0,425917.0,315.0,711.0
7028,7029,21,chaudenay-la-ville,CHAUDENAY-LA-VILLE,chaudenay la ville,Chaudenay-la-Ville,C35414,XTNLFL,21360,155,...,7,5.18,4.650000,47.1667,2570.0,52404.0,43859.0,470950.0,365.0,551.0
650,651,2,tannieres,TANNIERES,tannieres,Tannières,T562,TNRS,02220,735,...,5,2.55,3.550000,49.2833,1351.0,54768.0,33309.0,491727.0,64.0,141.0
3088,3089,9,villeneuve-09,VILLENEUVE,villeneuve,Villeneuve,V451,FLNF,09800,335,...,8,5.00,0.981666,42.9383,-1505.0,47709.0,5854.0,425618.0,546.0,1129.0

In [30]:
listCity.head(50)

,ville_id,ville_departement,ville_slug,ville_nom,ville_nom_simple,ville_nom_reel,ville_nom_soundex,ville_nom_metaphone,ville_code_postal,ville_commune,...,ville_densite_2010,ville_surface,ville_longitude_de,ville_latitude_deg,ville_longitude_grd,ville_latitude_grd,ville_longitude_dms,ville_latitude_dms,ville_zmin,ville_zmax
30437,30438,75,paris,PARIS,paris,Paris,P620,PRS,75001-75002-75003-75004-75005-75006-75007-7500...,56,...,21288,105.40,2.344450,48.86000,9.0,54289.0,22040.0,485136.0,0.0,0.0
4439,4440,13,marseille,MARSEILLE,marseille,Marseille,M624,MRSL,13001-13002-13003-13004-13005-13006-13007-1300...,55,...,3535,240.62,5.376390,43.29670,3377.0,48107.0,52235.0,431748.0,0.0,640.0
28152,28153,69,lyon,LYON,lyon,Lyon,L500,LYN,69001-69002-69003-69004-69005-69006-69007-6900...,123,...,10117,47.87,4.841390,45.75890,2783.0,50843.0,45029.0,454532.0,162.0,312.0
11718,11719,31,toulouse,TOULOUSE,toulouse,Toulouse,T420,TLS,31000-31100-31200-31300-31400-31500,555,...,3734,118.30,1.433330,43.60000,-994.0,48449.0,12631.0,433616.0,115.0,263.0
2049,2050,6,nice,NICE,nice,Nice,N200,NS,06000-06100-06200-06300,88,...,4773,71.92,7.250000,43.70000,5480.0,48558.0,71606.0,434207.0,0.0,520.0
16755,16756,44,nantes,NANTES,nantes,Nantes,N320,NNTS,44000-44100-44200-44300,109,...,4371,65.19,-1.550000,47.21670,-4323.0,52464.0,-13314.0,471302.0,2.0,52.0
27303,27304,67,strasbourg,STRASBOURG,strasbourg,Strasbourg,S362162,STRSBRK,67000-67100-67200,482,...,3472,78.26,7.750000,48.58330,6013.0,53982.0,74453.0,483501.0,132.0,151.0
13338,13339,34,montpellier,MONTPELLIER,montpellier,Montpellier,M3146,MNTPLR,34000-34070-34080-34090,172,...,4524,56.88,3.883330,43.60000,1711.0,48457.0,35236.0,433640.0,7.0,121.0
12678,12679,33,bordeaux,BORDEAUX,bordeaux,Bordeaux,B632,BRTKS,33000-33100-33200-33300-33800,63,...,4845,49.36,-0.566667,44.83330,-3240.0,49820.0,-3446.0,445016.0,1.0,42.0
22744,22745,59,lille,LILLE,lille,Lille,L000,LL,59000-59160-59260-59777-59800,350,...,6533,34.83,3.066670,50.63330,801.0,56258.0,30327.0,503755.0,17.0,45.0
13467,13468,35,rennes,RENNES,rennes,Rennes,R520,RNS,35000-35200-35700,238,...,4111,50.39,-1.683330,48.08330,-4463.0,53460.0,-14051.0,480651.0,20.0,74.0
19043,19044,51,reims,REIMS,reims,Reims,R520,RMS,51100,454,...,3837,46.90,4.033330,49.25000,1880.0,54739.0,40143.0,491555.0,74.0,137.0
31165,31166,76,havre,LE HAVRE,le havre,Le Havre,L160,LHFR,76600-76610-76620,351,...,3737,46.95,0.133333,49.50000,-2461.0,54999.0,716.0,492956.0,0.0,105.0
16123,16124,42,saint-etienne,SAINT-ETIENNE,saint etienne,Saint-Étienne,S535,SNTTN,42000-42100-42230,218,...,2141,79.97,4.400000,45.43330,2281.0,50482.0,42323.0,452602.0,422.0,1117.0
33676,33677,83,toulon,TOULON,toulon,Toulon,T450,TLN,83000-83100-83200,137,...,3840,42.84,5.933330,43.11670,3993.0,47917.0,55550.0,430730.0,0.0,589.0
14504,14505,38,grenoble,GRENOBLE,grenoble,Grenoble,G6514,KRNBL,38000-38100,185,...,8584,18.13,5.716670,45.16670,3766.0,50208.0,54335.0,451113.0,204.0,600.0
7232,7233,21,dijon,DIJON,dijon,Dijon,D250,TJN,21000-21100,231,...,3741,40.41,5.016670,47.31670,3006.0,52581.0,50231.0,471923.0,220.0,410.0
18072,18073,49,angers,ANGERS,angers,Angers,A5262,ANJRS,49000-49100,7,...,3455,42.70,-0.550000,47.46670,-3213.0,52748.0,-3320.0,472822.0,12.0,64.0
36666,36667,974,saint-denis,SAINT-DENIS,ste clotilde,Saint-Denis,S5352,SNTTNS,97490,411,...,1021,142.00,46.710700,1.71819,NaN,NaN,NaN,NaN,NaN,NaN
29482,29483,72,le-mans,LE MANS,le mans,Le Mans,L520,LMNS,72000-72100,181,...,2700,52.81,0.200000,48.00000,-2377.0,53338.0,1149.0,480015.0,38.0,134.0
4420,4421,13,aix-en-provence,AIX-EN-PROVENCE,aix en provence,Aix-en-Provence,A2516152,AKSNPRFNS,13080-13090-13100-13290-13540,1,...,760,186.08,5.433330,43.53330,3454.0,48364.0,52644.0,433140.0,73.0,501.0
11151,11152,29,brest,BREST,brest,Brest,B623,BRST,29200,19,...,2854,49.51,-4.483330,48.40000,-7581.0,53767.0,-42913.0,482324.0,0.0,103.0
28207,28208,69,villeurbanne,VILLEURBANNE,villeurbanne,Villeurbanne,V4615,FLRBN,69100,266,...,9996,14.52,4.883330,45.76670,2825.0,50851.0,45246.0,454558.0,165.0,189.0
11335,11336,30,nîmes,NIMES,nimes,Nîmes,N200,NMS,30000-30900,189,...,878,161.85,4.350000,43.83330,2248.0,48708.0,42136.0,435013.0,21.0,215.0
34487,34488,87,limoges,LIMOGES,limoges,Limoges,L520,LMJS,87000-87100-87280,85,...,1783,78.03,1.250000,45.85000,-1194.0,50927.0,11542.0,455004.0,209.0,431.0
25484,25485,63,clermont-ferrand,CLERMONT-FERRAND,clermont ferrand,Clermont-Ferrand,C46531653,KLRMNTFRNT,63000-63100,113,...,3277,42.67,3.083330,45.78330,834.0,50866.0,30513.0,454647.0,321.0,602.0
14123,14124,37,tours,TOURS,tours,Tours,T620,TRS,37000-37100-37200,261,...,3888,34.67,0.683333,47.38330,-1831.0,52659.0,4118.0,472334.0,44.0,109.0
32932,32933,80,amiens,AMIENS,amiens,Amiens,A520,AMNS,80000-80080-80090,21,...,2698,49.46,2.300000,49.90000,-43.0,55436.0,21752.0,495331.0,14.0,106.0
21913,21914,57,metz,METZ,metz,Metz,M320,MTS,57000-57050-57070,463,...,2878,41.94,6.166670,49.13330,4267.0,54578.0,61037.0,490711.0,162.0,256.0
9369,9370,25,besancon,BESANCON,besancon,Besançon,B2525,BSNKN,25000,56,...,1797,65.05,6.033330,47.25000,4094.0,52491.0,60117.0,471432.0,235.0,610.0
27143,27144,66,perpignan,PERPIGNAN,perpignan,Perpignan,P6125,PRPKNN,66000-66100,136,...,1724,68.07,2.883330,42.68330,620.0,47442.0,25341.0,424151.0,8.0,95.0
17161,17162,45,orleans,ORLEANS,orleans,Orléans,O6452,ORLNS,45000-45100,234,...,4154,27.48,1.900000,47.91670,-481.0,53225.0,15415.0,475408.0,90.0,124.0
35913,35914,92,boulogne-billancourt,BOULOGNE-BILLANCOURT,boulogne billancourt,Boulogne-Billancourt,B425145263,BLKNBLNKRT,92100,12,...,18509,6.17,2.250000,48.83330,-106.0,54262.0,21429.0,485007.0,28.0,40.0
28048,28049,68,mulhouse,MULHOUSE,mulhouse,Mulhouse,M420,MLHS,68100-68200,224,...,4940,22.18,7.333330,47.75000,5558.0,53054.0,72021.0,474455.0,231.0,336.0
5021,5022,14,caen,CAEN,caen,Caen,C500,KN,14000,118,...,4239,25.70,-0.350000,49.18330,-3008.0,54647.0,-2214.0,491056.0,2.0,73.0
30898,30899,76,rouen,ROUEN,rouen,Rouen,R500,RN,76000-76100,540,...,5188,21.38,1.083330,49.43330,-1371.0,54937.0,10609.0,492635.0,2.0,152.0
20553,20554,54,nancy,NANCY,nancy,Nancy,N200,NNS,54100,395,...,7023,15.01,6.200000,48.68330,4274.0,54103.0,61101.0,484134.0,188.0,353.0
35949,35950,93,saint-denis-93,SAINT-DENIS,saint denis,Saint-Denis,S5352,SNTTNS,93200-93210,66,...,8639,12.36,2.358330,48.93330,19.0,54373.0,22114.0,485608.0,23.0,46.0
36670,36671,974,saint-paul,SAINT-PAUL,st paul,Saint-Paul,S5314,SNTPL,97460,415,...,428,241.00,-21.003300,55.28330,NaN,NaN,NaN,NaN,NaN,NaN
36173,36174,95,argenteuil,ARGENTEUIL,argenteuil,Argenteuil,A62534,ARJNTL,95100,18,...,5988,17.22,2.250000,48.95000,-99.0,54387.0,21451.0,485652.0,21.0,169.0
35942,35943,93,montreuil-93,MONTREUIL,montreuil,Montreuil,M364,MNTRL,93100,48,...,11521,8.92,2.433330,48.86670,118.0,54289.0,22635.0,485137.0,52.0,117.0
22717,22718,59,roubaix,ROUBAIX,roubaix,Roubaix,R120,RBKS,59100,512,...,7158,13.23,3.166670,50.70000,938.0,56321.0,31051.0,504121.0,17.0,52.0
23099,23100,59,dunkerque,DUNKERQUE,dunkerque,Dunkerque,D5262,TNKRK,59140-59240-59430-59640-59279,183,...,2096,43.89,2.366670,51.05000,44.0,56709.0,22235.0,510216.0,0.0,17.0
23014,23015,59,tourcoing,TOURCOING,tourcoing,Tourcoing,T6252,TRKNK,59200,599,...,6051,15.19,3.150000,50.71670,915.0,56358.0,30937.0,504321.0,24.0,49.0
33837,33838,84,avignon,AVIGNON,avignon,Avignon,A125,AFKNN,84000,7,...,1381,64.91,4.816670,43.95000,2746.0,48832.0,44830.0,435655.0,10.0,122.0
35931,35932,92,nanterre,NANTERRE,nanterre,Nanterre,N360,NNTR,92000,50,...,7316,12.19,2.200000,48.90000,-148.0,54323.0,21213.0,485326.0,22.0,127.0
34242,34243,86,poitiers,POITIERS,poitiers,Poitiers,P362,PTRS,86000,194,...,2082,42.11,0.333333,46.58330,-2224.0,51757.0,2007.0,463452.0,65.0,144.0
36022,36023,94,creteil,CRETEIL,creteil,Créteil,C634,KRTL,94000,28,...,7852,11.46,2.466670,48.78330,139.0,54212.0,22743.0,484726.0,31.0,74.0
36608,36609,972,fort-de-france,FORT-DE-FRANCE,fort de france,Fort-de-France,F631652,FRTTFRNS,97234,209,...,1982,44.00,14.627000,-61.07320,NaN,NaN,NaN,NaN,NaN,NaN
31855,31856,78,versailles,VERSAILLES,versailles,Versailles,V6242,FRSLS,78000,646,...,3289,26.18,2.133330,48.80000,-225.0,54227.0,20803.0,484817.0,103.0,180.0